
# Define a multiline list of model names
MODELS=(
    "yentinglin/Taiwan-LLaMa-v0.0"
    "yentinglin/Taiwan-LLaMa-v0.9"
    "yentinglin/Taiwan-LLaMa-v1.0"
    "yentinglin/Taiwan-LLM-7B-v2.0-base"
    "yentinglin/Taiwan-LLM-7B-v2.0-chat"
    "yentinglin/Taiwan-LLM-7B-v2.0.1-chat"
    "yentinglin/Taiwan-LLM-7B-v2.1-chat"
    "yentinglin/Taiwan-LLM-13B-v2.0-base"
    "yentinglin/Taiwan-LLM-13B-v2.0-chat"
    "CohereForAI/c4ai-command-r-v01"
    "mistralai/Mixtral-8x7B-Instruct-v0.1"
    "mistralai/Mixtral-8x7B-v0.1"
    "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"
    "cognitivecomputations/dolphin-2.5-mixtral-8x7b"
    "google/gemma-7b"
    "google/gemma-7b-it"
    "google/gemma-2b"
    "google/gemma-2b-it"
    "meta-llama/Llama-2-70b-chat-hf"
    "meta-llama/Llama-2-70b-hf"
    "152334H/miqu-1-70b-sf"
    "Qwen/Qwen1.5-0.5B"
    "Qwen/Qwen1.5-1.8B"
    "Qwen/Qwen1.5-4B"
    "Qwen/Qwen1.5-7B"
    "Qwen/Qwen1.5-14B"
    "Qwen/Qwen1.5-72B"
    "Qwen/Qwen1.5-0.5B-Chat"
    "Qwen/Qwen1.5-1.8B-Chat"
    "Qwen/Qwen1.5-4B-Chat"
    "Qwen/Qwen1.5-7B-Chat"
    "Qwen/Qwen1.5-14B-Chat"
    "Qwen/Qwen1.5-72B-Chat"
    "01-ai/Yi-6B"
    "01-ai/Yi-9B"
    "01-ai/Yi-6B-Chat"
    "01-ai/Yi-34B-Chat"
    "01-ai/Yi-34B"
)

for MODEL in "${MODELS[@]}"; do
	sbatch eval.slurm "$MODEL"
done